import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class FoodOutlet {
    public static void main(String[] args) {

        final String string = "{\n"
                + "  \"page\": 1,\n"
                + "  \"per_page\": 10,\n"
                + "  \"total\": 40,\n"
                + "  \"total_pages\": 4,\n"
                + "  \"data\": [\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"Cafe Juanita\",\n"
                + "      \"estimated_cost\": 160,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.9,\n"
                + "        \"votes\": 16203\n"
                + "      },\n"
                + "      \"id\": 41\n"
                + "    },\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"Cafe Munir\",\n"
                + "      \"estimated_cost\": 160,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.9,\n"
                + "        \"votes\": 4699\n"
                + "      },\n"
                + "      \"id\": 42\n"
                + "    },\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"Flechazo\",\n"
                + "      \"estimated_cost\": 140,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.8,\n"
                + "        \"votes\": 2663\n"
                + "      },\n"
                + "      \"id\": 43\n"
                + "    },\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"Vanilla Sky\",\n"
                + "      \"estimated_cost\": 120,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.6,\n"
                + "        \"votes\": 645\n"
                + "      },\n"
                + "      \"id\": 44\n"
                + "    },\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"The Shambles\",\n"
                + "      \"estimated_cost\": 110,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.4,\n"
                + "        \"votes\": 2116\n"
                + "      },\n"
                + "      \"id\": 45\n"
                + "    },\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"Stories\",\n"
                + "      \"estimated_cost\": 150,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.5,\n"
                + "        \"votes\": 2087\n"
                + "      },\n"
                + "      \"id\": 46\n"
                + "    },\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"Big Pitcher\",\n"
                + "      \"estimated_cost\": 180,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.7,\n"
                + "        \"votes\": 9011\n"
                + "      },\n"
                + "      \"id\": 47\n"
                + "    },\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"The Black Pearl\",\n"
                + "      \"estimated_cost\": 150,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.8,\n"
                + "        \"votes\": 6976\n"
                + "      },\n"
                + "      \"id\": 48\n"
                + "    },\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"Truffles\",\n"
                + "      \"estimated_cost\": 90,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.7,\n"
                + "        \"votes\": 14611\n"
                + "      },\n"
                + "      \"id\": 49\n"
                + "    },\n"
                + "    {\n"
                + "      \"city\": \"Seattle\",\n"
                + "      \"name\": \"Biergarten\",\n"
                + "      \"estimated_cost\": 240,\n"
                + "      \"user_rating\": {\n"
                + "        \"average_rating\": 4.7,\n"
                + "        \"votes\": 299\n"
                + "      },\n"
                + "      \"id\": 410\n"
                + "    }\n"
                + "  ]\n"
                + "}";

        final String regex = "\\{.|\\n*\"data\":\\s|\\n*\\{.|\\n*\"name\":\\s*\"(.*?)\"";
        final Pattern pattern = Pattern.compile(regex);
        final Matcher matcher = pattern.matcher(string);

        while (matcher.find()) {
            for (int i = 1; i <= matcher.groupCount(); i++) {
                System.out.println(matcher.group(1));
            }
        }
    }
}
